=== BaSysTeam/BaSYS.Examples.ContractApproval/metadata/system/schemas/metaObjectStorableSettings.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "MetaObjectStorableSettings",
  "type": "object",
  "properties": {
    "uid": {
      "type": "string",
      "format": "guid"
    },
    "metaObjectKindUid": {
      "type": "string",
      "format": "guid"
    },
    "title": {
      "type": [
        "null",
        "string"
      ]
    },
    "name": {
      "type": [
        "null",
        "string"
      ]
    },
    "memo": {
      "type": [
        "null",
        "string"
      ]
    },
    "editMethod": {
      "$ref": "#/definitions/EditMethods"
    },
    "orderByExpression": {
      "type": [
        "null",
        "string"
      ]
    },
    "displayExpression": {
      "type": [
        "null",
        "string"
      ]
    },
    "listFormUid": {
      "type": [
        "null",
        "string"
      ],
      "format": "guid"
    },
    "itemFormUid": {
      "type": [
        "null",
        "string"
      ],
      "format": "guid"
    },
    "showMainImage": {
      "type": "boolean"
    },
    "saveHistory": {
      "$ref": "#/definitions/SaveHistoryMode"
    },
    "version": {
      "type": "integer",
      "format": "int64"
    },
    "isActive": {
      "type": "boolean"
    },
    "header": {
      "oneOf": [
        {
          "type": "null"
        },
        {
          "$ref": "#/definitions/MetaObjectTable"
        }
      ]
    },
    "detailTables": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "$ref": "#/definitions/MetaObjectTable"
      }
    },
    "commands": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "$ref": "#/definitions/MetaObjectCommand"
      }
    },
    "recordsSources": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "$ref": "#/definitions/RecordsSourceItem"
      }
    },
    "recordsSettings": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "$ref": "#/definitions/MetaObjectRecordsSettingsItem"
      }
    }
  },
  "definitions": {
    "EditMethods": {
      "type": "integer",
      "description": "",
      "x-enumNames": [
        "Page",
        "Modal"
      ],
      "enum": [
        0,
        1
      ]
    },
    "SaveHistoryMode": {
      "type": "integer",
      "description": "",
      "x-enumNames": [
        "Inherit",
        "Disabled",
        "Enabled"
      ],
      "enum": [
        0,
        1,
        2
      ]
    },
    "MetaObjectTable": {
      "type": "object",
      "properties": {
        "uid": {
          "type": "string",
          "format": "guid"
        },
        "title": {
          "type": [
            "null",
            "string"
          ]
        },
        "name": {
          "type": [
            "null",
            "string"
          ]
        },
        "memo": {
          "type": [
            "null",
            "string"
          ]
        },
        "autoClearMethod": {
          "$ref": "#/definitions/AutoClearMethods"
        },
        "columns": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/MetaObjectTableColumn"
          }
        },
        "indexes": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/MetaObjectTableIndex"
          }
        },
        "columnsWithFormulas": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/MetaObjectTableColumn"
          }
        },
        "primaryKey": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "#/definitions/MetaObjectTableColumn"
            }
          ]
        }
      }
    },
    "AutoClearMethods": {
      "type": "integer",
      "description": "",
      "x-enumNames": [
        "None",
        "WhenCopy",
        "WhenCreateFrom",
        "WhenCopyOrCreateFrom"
      ],
      "enum": [
        0,
        1,
        2,
        3
      ]
    },
    "MetaObjectTableColumn": {
      "type": "object",
      "properties": {
        "uid": {
          "type": "string",
          "format": "guid"
        },
        "kind": {
          "$ref": "#/definitions/DataObjectColumnKinds"
        },
        "standardColumnUid": {
          "type": [
            "null",
            "string"
          ],
          "format": "guid"
        },
        "title": {
          "type": [
            "null",
            "string"
          ]
        },
        "name": {
          "type": [
            "null",
            "string"
          ]
        },
        "formula": {
          "type": [
            "null",
            "string"
          ]
        },
        "itemsSource": {
          "type": [
            "null",
            "string"
          ]
        },
        "autoClearMethod": {
          "$ref": "#/definitions/AutoClearMethods"
        },
        "isStandard": {
          "type": "boolean"
        },
        "dataSettings": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "#/definitions/MetaObjectTableColumnDataSettings"
            }
          ]
        },
        "renderSettings": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "#/definitions/MetaObjectTableColumnRenderSettings"
            }
          ]
        },
        "dependencies": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/DependencyInfo"
          }
        }
      }
    },
    "DataObjectColumnKinds": {
      "type": "integer",
      "description": "",
      "x-enumNames": [
        "Stored",
        "Virtual"
      ],
      "enum": [
        0,
        1
      ]
    },
    "MetaObjectTableColumnDataSettings": {
      "type": "object",
      "properties": {
        "dataTypeUid": {
          "type": "string",
          "format": "guid"
        },
        "stringLength": {
          "type": "integer",
          "format": "int32"
        },
        "numberDigits": {
          "type": "integer",
          "format": "int32"
        },
        "primaryKey": {
          "type": "boolean"
        },
        "required": {
          "type": "boolean"
        },
        "unique": {
          "type": "boolean"
        },
        "defaultValue": {
          "type": [
            "null",
            "string"
          ]
        }
      }
    },
    "MetaObjectTableColumnRenderSettings": {
      "type": "object",
      "properties": {
        "controlKindUid": {
          "type": [
            "null",
            "string"
          ]
        },
        "showInItem": {
          "type": "boolean"
        },
        "showInList": {
          "type": "boolean"
        },
        "listColumnWidth": {
          "type": [
            "null",
            "string"
          ]
        }
      }
    },
    "DependencyInfo": {
      "type": "object",
      "properties": {
        "kind": {
          "$ref": "#/definitions/DependencyKinds"
        },
        "fieldUid": {
          "type": "string",
          "format": "guid"
        },
        "tableUid": {
          "type": "string",
          "format": "guid"
        }
      }
    },
    "DependencyKinds": {
      "type": "integer",
      "description": "",
      "x-enumNames": [
        "HeaderField",
        "RowField",
        "Table"
      ],
      "enum": [
        0,
        1,
        2
      ]
    },
    "MetaObjectTableIndex": {
      "type": "object",
      "properties": {
        "uid": {
          "type": "string",
          "format": "guid"
        },
        "columns": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/MetaObjectTableIndexColumn"
          }
        }
      }
    },
    "MetaObjectTableIndexColumn": {
      "type": "object",
      "properties": {
        "columnUid": {
          "type": "string",
          "format": "guid"
        },
        "direction": {
          "$ref": "#/definitions/IndexDirections"
        }
      }
    },
    "IndexDirections": {
      "type": "integer",
      "description": "",
      "x-enumNames": [
        "Descending",
        "Ascending"
      ],
      "enum": [
        0,
        1
      ]
    },
    "MetaObjectCommand": {
      "type": "object",
      "properties": {
        "uid": {
          "type": "string",
          "format": "guid"
        },
        "tableUid": {
          "type": "string",
          "format": "guid"
        },
        "kind": {
          "$ref": "#/definitions/MetaObjectCommandKinds"
        },
        "title": {
          "type": [
            "null",
            "string"
          ]
        },
        "name": {
          "type": [
            "null",
            "string"
          ]
        },
        "expression": {
          "type": [
            "null",
            "string"
          ],
          "description": "JavaScript expression for this command. In export packages the value is a relative file reference (e.g. 'Catalog.Customer.command.fill_defaults.bjs') pointing to a companion .bjs file; the import pipeline resolves it back to inline code automatically.",
          "x-example": "Catalog.Customer.command.fill_defaults.bjs"
        },
        "memo": {
          "type": [
            "null",
            "string"
          ]
        },
        "isActive": {
          "type": "boolean"
        },
        "parameters": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/MetaObjectCommandParameter"
          }
        }
      }
    },
    "MetaObjectCommandKinds": {
      "type": "integer",
      "description": "",
      "x-enumNames": [
        "Custom",
        "Fill",
        "PickUp"
      ],
      "enum": [
        0,
        1,
        2
      ]
    },
    "MetaObjectCommandParameter": {
      "type": "object",
      "properties": {
        "name": {
          "type": [
            "null",
            "string"
          ]
        },
        "value": {
          "type": [
            "null",
            "string"
          ]
        },
        "dbType": {
          "$ref": "#/definitions/DbType"
        }
      }
    },
    "DbType": {
      "type": "integer",
      "description": "",
      "x-enumNames": [
        "AnsiString",
        "Binary",
        "Byte",
        "Boolean",
        "Currency",
        "Date",
        "DateTime",
        "Decimal",
        "Double",
        "Guid",
        "Int16",
        "Int32",
        "Int64",
        "Object",
        "SByte",
        "Single",
        "String",
        "Time",
        "UInt16",
        "UInt32",
        "UInt64",
        "VarNumeric",
        "AnsiStringFixedLength",
        "StringFixedLength",
        "Xml",
        "DateTime2",
        "DateTimeOffset"
      ],
      "enum": [
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20,
        21,
        22,
        23,
        25,
        26,
        27
      ]
    },
    "RecordsSourceItem": {
      "type": "object",
      "properties": {
        "uid": {
          "type": "string",
          "format": "guid"
        },
        "title": {
          "type": [
            "null",
            "string"
          ]
        },
        "expression": {
          "type": [
            "null",
            "string"
          ],
          "description": "JavaScript expression for this records source. In export packages the value is a relative file reference (e.g. 'Catalog.Customer.records_source.main.bjs') pointing to a companion .bjs file; the import pipeline resolves it back to inline code automatically.",
          "x-example": "Catalog.Customer.records_source.main.bjs"
        }
      }
    },
    "MetaObjectRecordsSettingsItem": {
      "type": "object",
      "properties": {
        "destinationMetaObjectUid": {
          "type": "string",
          "format": "guid"
        },
        "rows": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/MetaObjectRecordsSettingsRow"
          }
        }
      }
    },
    "MetaObjectRecordsSettingsRow": {
      "type": "object",
      "properties": {
        "uid": {
          "type": "string",
          "format": "guid"
        },
        "sourceUid": {
          "type": "string",
          "format": "guid"
        },
        "direction": {
          "$ref": "#/definitions/RegisterRecordDirections"
        },
        "condition": {
          "type": [
            "null",
            "string"
          ]
        },
        "columns": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/MetaObjectRecordsSettingsColumn"
          }
        }
      }
    },
    "RegisterRecordDirections": {
      "type": "integer",
      "description": "",
      "x-enumNames": [
        "Plus",
        "Minus"
      ],
      "enum": [
        0,
        1
      ]
    },
    "MetaObjectRecordsSettingsColumn": {
      "type": "object",
      "properties": {
        "destinationColumnUid": {
          "type": "string",
          "format": "guid"
        },
        "expression": {
          "type": [
            "null",
            "string"
          ]
        }
      }
    }
  }
}

=== BaSysTeam/BaSYS.Examples.ContractApproval/enum/contract_kind/enum.contract_kind.json
{
  "$schema": "../../system/schemas/metaObjectStorableSettings.schema.json",
  "uid": "f1a2b3c4-d5e6-4789-9abc-def012345678",
  "metaObjectKindUid": "5449a8ad-9359-41b2-8ff2-3f415eb4da76",
  "title": "Вид договора",
  "name": "contract_kind",
  "memo": "Виды договоров: аренды, поставки, лизинг и т.п.",
  "editMethod": 0,
  "orderByExpression": "",
  "displayExpression": "",
  "listFormUid": null,
  "itemFormUid": null,
  "showMainImage": false,
  "version": 0,
  "isActive": true,
  "header": {
    "uid": "e2b3c4d5-e6f7-489a-9bcd-ef0123456789",
    "title": "header",
    "name": "header",
    "memo": "",
    "autoClearMethod": 0,
    "columns": [
      {
        "uid": "d3c4d5e6-f7a8-49ab-9cde-f01234567890",
        "kind": 0,
        "standardColumnUid": "3cceebad-7d5a-4943-a102-6267e22227a8",
        "title": "Имя",
        "name": "name",
        "formula": "",
        "itemsSource": "",
        "autoClearMethod": 0,
        "isStandard": true,
        "dataSettings": {
          "dataTypeUid": "0234c067-7868-46b2-ba8e-e22fae5255cb",
          "stringLength": 20,
          "numberDigits": 2,
          "primaryKey": true,
          "required": false,
          "unique": false,
          "defaultValue": null
        },
        "renderSettings": {
          "controlKindUid": "",
          "showInItem": true,
          "showInList": true,
          "listColumnWidth": ""
        },
        "dependencies": []
      },
      {
        "uid": "c4d5e6f7-a8b9-4abc-9def-012345678901",
        "kind": 0,
        "standardColumnUid": "1e0063d0-288d-494a-8761-1185300d571d",
        "title": "Удалено",
        "name": "is_deleted",
        "formula": "",
        "itemsSource": "",
        "autoClearMethod": 0,
        "isStandard": true,
        "dataSettings": {
          "dataTypeUid": "4bff64cf-eb01-4933-9f3d-b902336751f4",
          "stringLength": 100,
          "numberDigits": 2,
          "primaryKey": false,
          "required": false,
          "unique": false,
          "defaultValue": null
        },
        "renderSettings": {
          "controlKindUid": "",
          "showInItem": true,
          "showInList": false,
          "listColumnWidth": ""
        },
        "dependencies": []
      },
      {
        "uid": "b5e6f7a8-b9ca-4bcd-9ef0-123456789012",
        "kind": 0,
        "standardColumnUid": "e647fb57-470e-4547-9a94-2be0f3d0985e",
        "title": "Код",
        "name": "code",
        "formula": "",
        "itemsSource": "",
        "autoClearMethod": 0,
        "isStandard": true,
        "dataSettings": {
          "dataTypeUid": "0234c067-7868-46b2-ba8e-e22fae5255cb",
          "stringLength": 3,
          "numberDigits": 2,
          "primaryKey": false,
          "required": true,
          "unique": true,
          "defaultValue": null
        },
        "renderSettings": {
          "controlKindUid": "",
          "showInItem": true,
          "showInList": true,
          "listColumnWidth": ""
        },
        "dependencies": []
      },
      {
        "uid": "a6f7a8b9-cadb-4cde-9f01-234567890123",
        "kind": 0,
        "standardColumnUid": "91a26ae4-5723-4109-8322-7e4e59129239",
        "title": "Заголовок",
        "name": "title",
        "formula": "",
        "itemsSource": "",
        "autoClearMethod": 0,
        "isStandard": true,
        "dataSettings": {
          "dataTypeUid": "0234c067-7868-46b2-ba8e-e22fae5255cb",
          "stringLength": 100,
          "numberDigits": 2,
          "primaryKey": false,
          "required": true,
          "unique": false,
          "defaultValue": null
        },
        "renderSettings": {
          "controlKindUid": "",
          "showInItem": true,
          "showInList": true,
          "listColumnWidth": ""
        },
        "dependencies": []
      }
    ],
    "indexes": [
      {
        "uid": "97a8b9ca-dbec-4def-9012-345678901234",
        "columns": [
          {
            "columnUid": "c4d5e6f7-a8b9-4abc-9def-012345678901",
            "direction": 0
          }
        ]
      },
      {
        "uid": "88b9cadb-ecfd-4ef0-9123-456789012345",
        "columns": [
          {
            "columnUid": "b5e6f7a8-b9ca-4bcd-9ef0-123456789012",
            "direction": 0
          }
        ]
      }
    ]
  },
  "detailTables": [],
  "commands": [],
  "recordsSources": [],
  "recordsSettings": []
}

=== BaSysTeam/BaSYS.Examples.ContractApproval/metadata/enum/approval_role/enum.approval_role.json
{
  "$schema": "../../system/schemas/metaObjectStorableSettings.schema.json",
  "uid": "c1d2e3f4-a5b6-47c8-9d0e-1f2a3b4c5d6e",
  "metaObjectKindUid": "5449a8ad-9359-41b2-8ff2-3f415eb4da76",
  "title": "Роль согласования",
  "name": "approval_role",
  "memo": "Роль участника в процессе согласования договора",
  "editMethod": 0,
  "orderByExpression": "",
  "displayExpression": "",
  "listFormUid": null,
  "itemFormUid": null,
  "showMainImage": false,
  "saveHistory": 0,
  "version": 0,
  "isActive": true,
  "header": {
    "uid": "d2e3f4a5-b6c7-48d9-8e0f-2a3b4c5d6e7f",
    "title": "header",
    "name": "header",
    "memo": "",
    "autoClearMethod": 0,
    "columns": [
      {
        "uid": "e3f4a5b6-c7d8-49e0-9f1a-3b4c5d6e7f80",
        "kind": 0,
        "standardColumnUid": "3cceebad-7d5a-4943-a102-6267e22227a8",
        "title": "Имя",
        "name": "name",
        "formula": "",
        "itemsSource": "",
        "autoClearMethod": 0,
        "isStandard": true,
        "dataSettings": {
          "dataTypeUid": "0234c067-7868-46b2-ba8e-e22fae5255cb",
          "stringLength": 20,
          "numberDigits": 2,
          "primaryKey": true,
          "required": false,
          "unique": false,
          "defaultValue": null
        },
        "renderSettings": {
          "controlKindUid": "",
          "showInItem": true,
          "showInList": true,
          "listColumnWidth": ""
        },
        "dependencies": []
      },
      {
        "uid": "f4a5b6c7-d8e9-4a01-8b2c-4d5e6f708192",
        "kind": 0,
        "standardColumnUid": "1e0063d0-288d-494a-8761-1185300d571d",
        "title": "Удалено",
        "name": "is_deleted",
        "formula": "",
        "itemsSource": "",
        "autoClearMethod": 0,
        "isStandard": true,
        "dataSettings": {
          "dataTypeUid": "4bff64cf-eb01-4933-9f3d-b902336751f4",
          "stringLength": 100,
          "numberDigits": 2,
          "primaryKey": false,
          "required": false,
          "unique": false,
          "defaultValue": null
        },
        "renderSettings": {
          "controlKindUid": "",
          "showInItem": true,
          "showInList": false,
          "listColumnWidth": ""
        },
        "dependencies": []
      },
      {
        "uid": "a5b6c7d8-e9f0-4b12-9c3d-5e6f70819203",
        "kind": 0,
        "standardColumnUid": "e647fb57-470e-4547-9a94-2be0f3d0985e",
        "title": "Код",
        "name": "code",
        "formula": "",
        "itemsSource": "",
        "autoClearMethod": 0,
        "isStandard": true,
        "dataSettings": {
          "dataTypeUid": "0234c067-7868-46b2-ba8e-e22fae5255cb",
          "stringLength": 3,
          "numberDigits": 2,
          "primaryKey": false,
          "required": true,
          "unique": true,
          "defaultValue": null
        },
        "renderSettings": {
          "controlKindUid": "",
          "showInItem": true,
          "showInList": true,
          "listColumnWidth": ""
        },
        "dependencies": []
      },
      {
        "uid": "b6c7d8e9-f0a1-4c23-8d4e-6f7081920314",
        "kind": 0,
        "standardColumnUid": "91a26ae4-5723-4109-8322-7e4e59129239",
        "title": "Заголовок",
        "name": "title",
        "formula": "",
        "itemsSource": "",
        "autoClearMethod": 0,
        "isStandard": true,
        "dataSettings": {
          "dataTypeUid": "0234c067-7868-46b2-ba8e-e22fae5255cb",
          "stringLength": 100,
          "numberDigits": 2,
          "primaryKey": false,
          "required": true,
          "unique": false,
          "defaultValue": null
        },
        "renderSettings": {
          "controlKindUid": "",
          "showInItem": true,
          "showInList": true,
          "listColumnWidth": ""
        },
        "dependencies": []
      }
    ],
    "indexes": [
      {
        "uid": "c7d8e9f0-a1b2-4d34-9e5f-708192031425",
        "columns": [
          {
            "columnUid": "f4a5b6c7-d8e9-4a01-8b2c-4d5e6f708192",
            "direction": 0
          }
        ]
      },
      {
        "uid": "d8e9f0a1-b2c3-4e45-8f60-819203142536",
        "columns": [
          {
            "columnUid": "a5b6c7d8-e9f0-4b12-9c3d-5e6f70819203",
            "direction": 0
          }
        ]
      }
    ]
  },
  "detailTables": [],
  "commands": [],
  "recordsSources": [],
  "recordsSettings": []
}

=== BaSysTeam/BaSYS.Examples.ContractApproval/metadata/enum/contract_priority/enum.contract_priority.json
{
  "$schema": "../../system/schemas/metaObjectStorableSettings.schema.json",
  "uid": "8aeea012-aba9-426a-a6a2-b02f9d76eab6",
  "metaObjectKindUid": "5449a8ad-9359-41b2-8ff2-3f415eb4da76",
  "title": "Приоритет договора",
  "name": "contract_priority",
  "memo": "Приоритет договора",
  "editMethod": 0,
  "orderByExpression": "",
  "displayExpression": "",
  "listFormUid": null,
  "itemFormUid": null,
  "showMainImage": false,
  "saveHistory": 0,
  "version": 0,
  "isActive": true,
  "header": {
    "uid": "1a4f017c-8799-4f1d-bc81-5353b5d2bc7b",
    "title": "header",
    "name": "header",
    "memo": "",
    "autoClearMethod": 0,
    "columns": [
      {
        "uid": "ecd90c57-ac9d-4660-abbf-fb182d902ce0",
        "kind": 0,
        "standardColumnUid": "3cceebad-7d5a-4943-a102-6267e22227a8",
        "title": "Имя",
        "name": "name",
        "formula": "",
        "itemsSource": "",
        "autoClearMethod": 0,
        "isStandard": true,
        "dataSettings": {
          "dataTypeUid": "0234c067-7868-46b2-ba8e-e22fae5255cb",
          "stringLength": 20,
          "numberDigits": 2,
          "primaryKey": true,
          "required": false,
          "unique": false,
          "defaultValue": null
        },
        "renderSettings": {
          "controlKindUid": "",
          "showInItem": true,
          "showInList": true,
          "listColumnWidth": ""
        },
        "dependencies": []
      },
      {
        "uid": "473fa6f9-5bb1-4003-b809-2d8b660878f6",
        "kind": 0,
        "standardColumnUid": "1e0063d0-288d-494a-8761-1185300d571d",
        "title": "Удалено",
        "name": "is_deleted",
        "formula": "",
        "itemsSource": "",
        "autoClearMethod": 0,
        "isStandard": true,
        "dataSettings": {
          "dataTypeUid": "4bff64cf-eb01-4933-9f3d-b902336751f4",
          "stringLength": 100,
          "numberDigits": 2,
          "primaryKey": false,
          "required": false,
          "unique": false,
          "defaultValue": null
        },
        "renderSettings": {
          "controlKindUid": "",
          "showInItem": true,
          "showInList": false,
          "listColumnWidth": ""
        },
        "dependencies": []
      },
      {
        "uid": "90663839-48e1-4858-b1ae-f56d082d7148",
        "kind": 0,
        "standardColumnUid": "e647fb57-470e-4547-9a94-2be0f3d0985e",
        "title": "Код",
        "name": "code",
        "formula": "",
        "itemsSource": "",
        "autoClearMethod": 0,
        "isStandard": true,
        "dataSettings": {
          "dataTypeUid": "0234c067-7868-46b2-ba8e-e22fae5255cb",
          "stringLength": 3,
          "numberDigits": 2,
          "primaryKey": false,
          "required": true,
          "unique": true,
          "defaultValue": null
        },
        "renderSettings": {
          "controlKindUid": "",
          "showInItem": true,
          "showInList": true,
          "listColumnWidth": ""
        },
        "dependencies": []
      },
      {
        "uid": "0e34c69f-3220-4b74-af66-85ce32db7da4",
        "kind": 0,
        "standardColumnUid": "91a26ae4-5723-4109-8322-7e4e59129239",
        "title": "Заголовок",
        "name": "title",
        "formula": "",
        "itemsSource": "",
        "autoClearMethod": 0,
        "isStandard": true,
        "dataSettings": {
          "dataTypeUid": "0234c067-7868-46b2-ba8e-e22fae5255cb",
          "stringLength": 100,
          "numberDigits": 2,
          "primaryKey": false,
          "required": true,
          "unique": false,
          "defaultValue": null
        },
        "renderSettings": {
          "controlKindUid": "",
          "showInItem": true,
          "showInList": true,
          "listColumnWidth": ""
        },
        "dependencies": []
      }
    ],
    "indexes": [
      {
        "uid": "0c7e9be0-cca2-40a8-ae85-98e35f217a17",
        "columns": [
          {
            "columnUid": "473fa6f9-5bb1-4003-b809-2d8b660878f6",
            "direction": 0
          }
        ]
      },
      {
        "uid": "71de2731-c0ed-4f8f-a646-49f2cad20c94",
        "columns": [
          {
            "columnUid": "90663839-48e1-4858-b1ae-f56d082d7148",
            "direction": 0
          }
        ]
      }
    ]
  },
  "detailTables": [],
  "commands": [],
  "recordsSources": [],
  "recordsSettings": []
}
