=== BaSysTeam/BaSYS.Examples.ContractApproval/metadata/system/schemas/metaObjectStorableSettings.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "MetaObjectStorableSettings",
  "type": "object",
  "properties": {
    "uid": {
      "type": "string",
      "format": "guid"
    },
    "metaObjectKindUid": {
      "type": "string",
      "format": "guid"
    },
    "title": {
      "type": [
        "null",
        "string"
      ]
    },
    "name": {
      "type": [
        "null",
        "string"
      ]
    },
    "memo": {
      "type": [
        "null",
        "string"
      ]
    },
    "editMethod": {
      "$ref": "#/definitions/EditMethods"
    },
    "orderByExpression": {
      "type": [
        "null",
        "string"
      ]
    },
    "displayExpression": {
      "type": [
        "null",
        "string"
      ]
    },
    "listFormUid": {
      "type": [
        "null",
        "string"
      ],
      "format": "guid"
    },
    "itemFormUid": {
      "type": [
        "null",
        "string"
      ],
      "format": "guid"
    },
    "showMainImage": {
      "type": "boolean"
    },
    "saveHistory": {
      "$ref": "#/definitions/SaveHistoryMode"
    },
    "version": {
      "type": "integer",
      "format": "int64"
    },
    "isActive": {
      "type": "boolean"
    },
    "header": {
      "oneOf": [
        {
          "type": "null"
        },
        {
          "$ref": "#/definitions/MetaObjectTable"
        }
      ]
    },
    "detailTables": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "$ref": "#/definitions/MetaObjectTable"
      }
    },
    "commands": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "$ref": "#/definitions/MetaObjectCommand"
      }
    },
    "recordsSources": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "$ref": "#/definitions/RecordsSourceItem"
      }
    },
    "recordsSettings": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "$ref": "#/definitions/MetaObjectRecordsSettingsItem"
      }
    }
  },
  "definitions": {
    "EditMethods": {
      "type": "integer",
      "description": "",
      "x-enumNames": [
        "Page",
        "Modal"
      ],
      "enum": [
        0,
        1
      ]
    },
    "SaveHistoryMode": {
      "type": "integer",
      "description": "",
      "x-enumNames": [
        "Inherit",
        "Disabled",
        "Enabled"
      ],
      "enum": [
        0,
        1,
        2
      ]
    },
    "MetaObjectTable": {
      "type": "object",
      "properties": {
        "uid": {
          "type": "string",
          "format": "guid"
        },
        "title": {
          "type": [
            "null",
            "string"
          ]
        },
        "name": {
          "type": [
            "null",
            "string"
          ]
        },
        "memo": {
          "type": [
            "null",
            "string"
          ]
        },
        "autoClearMethod": {
          "$ref": "#/definitions/AutoClearMethods"
        },
        "columns": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/MetaObjectTableColumn"
          }
        },
        "indexes": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/MetaObjectTableIndex"
          }
        },
        "columnsWithFormulas": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/MetaObjectTableColumn"
          }
        },
        "primaryKey": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "#/definitions/MetaObjectTableColumn"
            }
          ]
        }
      }
    },
    "AutoClearMethods": {
      "type": "integer",
      "description": "",
      "x-enumNames": [
        "None",
        "WhenCopy",
        "WhenCreateFrom",
        "WhenCopyOrCreateFrom"
      ],
      "enum": [
        0,
        1,
        2,
        3
      ]
    },
    "MetaObjectTableColumn": {
      "type": "object",
      "properties": {
        "uid": {
          "type": "string",
          "format": "guid"
        },
        "kind": {
          "$ref": "#/definitions/DataObjectColumnKinds"
        },
        "standardColumnUid": {
          "type": [
            "null",
            "string"
          ],
          "format": "guid"
        },
        "title": {
          "type": [
            "null",
            "string"
          ]
        },
        "name": {
          "type": [
            "null",
            "string"
          ]
        },
        "formula": {
          "type": [
            "null",
            "string"
          ]
        },
        "itemsSource": {
          "type": [
            "null",
            "string"
          ]
        },
        "autoClearMethod": {
          "$ref": "#/definitions/AutoClearMethods"
        },
        "isStandard": {
          "type": "boolean"
        },
        "dataSettings": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "#/definitions/MetaObjectTableColumnDataSettings"
            }
          ]
        },
        "renderSettings": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "#/definitions/MetaObjectTableColumnRenderSettings"
            }
          ]
        },
        "dependencies": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/DependencyInfo"
          }
        }
      }
    },
    "DataObjectColumnKinds": {
      "type": "integer",
      "description": "",
      "x-enumNames": [
        "Stored",
        "Virtual"
      ],
      "enum": [
        0,
        1
      ]
    },
    "MetaObjectTableColumnDataSettings": {
      "type": "object",
      "properties": {
        "dataTypeUid": {
          "type": "string",
          "format": "guid"
        },
        "stringLength": {
          "type": "integer",
          "format": "int32"
        },
        "numberDigits": {
          "type": "integer",
          "format": "int32"
        },
        "primaryKey": {
          "type": "boolean"
        },
        "required": {
          "type": "boolean"
        },
        "unique": {
          "type": "boolean"
        },
        "defaultValue": {
          "type": [
            "null",
            "string"
          ]
        }
      }
    },
    "MetaObjectTableColumnRenderSettings": {
      "type": "object",
      "properties": {
        "controlKindUid": {
          "type": [
            "null",
            "string"
          ]
        },
        "showInItem": {
          "type": "boolean"
        },
        "showInList": {
          "type": "boolean"
        },
        "listColumnWidth": {
          "type": [
            "null",
            "string"
          ]
        }
      }
    },
    "DependencyInfo": {
      "type": "object",
      "properties": {
        "kind": {
          "$ref": "#/definitions/DependencyKinds"
        },
        "fieldUid": {
          "type": "string",
          "format": "guid"
        },
        "tableUid": {
          "type": "string",
          "format": "guid"
        }
      }
    },
    "DependencyKinds": {
      "type": "integer",
      "description": "",
      "x-enumNames": [
        "HeaderField",
        "RowField",
        "Table"
      ],
      "enum": [
        0,
        1,
        2
      ]
    },
    "MetaObjectTableIndex": {
      "type": "object",
      "properties": {
        "uid": {
          "type": "string",
          "format": "guid"
        },
        "columns": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/MetaObjectTableIndexColumn"
          }
        }
      }
    },
    "MetaObjectTableIndexColumn": {
      "type": "object",
      "properties": {
        "columnUid": {
          "type": "string",
          "format": "guid"
        },
        "direction": {
          "$ref": "#/definitions/IndexDirections"
        }
      }
    },
    "IndexDirections": {
      "type": "integer",
      "description": "",
      "x-enumNames": [
        "Descending",
        "Ascending"
      ],
      "enum": [
        0,
        1
      ]
    },
    "MetaObjectCommand": {
      "type": "object",
      "properties": {
        "uid": {
          "type": "string",
          "format": "guid"
        },
        "tableUid": {
          "type": "string",
          "format": "guid"
        },
        "kind": {
          "$ref": "#/definitions/MetaObjectCommandKinds"
        },
        "title": {
          "type": [
            "null",
            "string"
          ]
        },
        "name": {
          "type": [
            "null",
            "string"
          ]
        },
        "expression": {
          "type": [
            "null",
            "string"
          ],
          "description": "JavaScript expression for this command. In export packages the value is a relative file reference (e.g. 'Catalog.Customer.command.fill_defaults.bjs') pointing to a companion .bjs file; the import pipeline resolves it back to inline code automatically.",
          "x-example": "Catalog.Customer.command.fill_defaults.bjs"
        },
        "memo": {
          "type": [
            "null",
            "string"
          ]
        },
        "isActive": {
          "type": "boolean"
        },
        "parameters": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/MetaObjectCommandParameter"
          }
        }
      }
    },
    "MetaObjectCommandKinds": {
      "type": "integer",
      "description": "",
      "x-enumNames": [
        "Custom",
        "Fill",
        "PickUp"
      ],
      "enum": [
        0,
        1,
        2
      ]
    },
    "MetaObjectCommandParameter": {
      "type": "object",
      "properties": {
        "name": {
          "type": [
            "null",
            "string"
          ]
        },
        "value": {
          "type": [
            "null",
            "string"
          ]
        },
        "dbType": {
          "$ref": "#/definitions/DbType"
        }
      }
    },
    "DbType": {
      "type": "integer",
      "description": "",
      "x-enumNames": [
        "AnsiString",
        "Binary",
        "Byte",
        "Boolean",
        "Currency",
        "Date",
        "DateTime",
        "Decimal",
        "Double",
        "Guid",
        "Int16",
        "Int32",
        "Int64",
        "Object",
        "SByte",
        "Single",
        "String",
        "Time",
        "UInt16",
        "UInt32",
        "UInt64",
        "VarNumeric",
        "AnsiStringFixedLength",
        "StringFixedLength",
        "Xml",
        "DateTime2",
        "DateTimeOffset"
      ],
      "enum": [
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20,
        21,
        22,
        23,
        25,
        26,
        27
      ]
    },
    "RecordsSourceItem": {
      "type": "object",
      "properties": {
        "uid": {
          "type": "string",
          "format": "guid"
        },
        "title": {
          "type": [
            "null",
            "string"
          ]
        },
        "expression": {
          "type": [
            "null",
            "string"
          ],
          "description": "JavaScript expression for this records source. In export packages the value is a relative file reference (e.g. 'Catalog.Customer.records_source.main.bjs') pointing to a companion .bjs file; the import pipeline resolves it back to inline code automatically.",
          "x-example": "Catalog.Customer.records_source.main.bjs"
        }
      }
    },
    "MetaObjectRecordsSettingsItem": {
      "type": "object",
      "properties": {
        "destinationMetaObjectUid": {
          "type": "string",
          "format": "guid"
        },
        "rows": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/MetaObjectRecordsSettingsRow"
          }
        }
      }
    },
    "MetaObjectRecordsSettingsRow": {
      "type": "object",
      "properties": {
        "uid": {
          "type": "string",
          "format": "guid"
        },
        "sourceUid": {
          "type": "string",
          "format": "guid"
        },
        "direction": {
          "$ref": "#/definitions/RegisterRecordDirections"
        },
        "condition": {
          "type": [
            "null",
            "string"
          ]
        },
        "columns": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/MetaObjectRecordsSettingsColumn"
          }
        }
      }
    },
    "RegisterRecordDirections": {
      "type": "integer",
      "description": "",
      "x-enumNames": [
        "Plus",
        "Minus"
      ],
      "enum": [
        0,
        1
      ]
    },
    "MetaObjectRecordsSettingsColumn": {
      "type": "object",
      "properties": {
        "destinationColumnUid": {
          "type": "string",
          "format": "guid"
        },
        "expression": {
          "type": [
            "null",
            "string"
          ]
        }
      }
    }
  }
}

=== BaSysTeam/BaSYS.Examples.ContractApproval/metadata/operation/test_operation/operation.test_operation.json
{
  "$schema": "../../system/schemas/metaObjectStorableSettings.schema.json",
  "uid": "a1b2c3d4-0001-4a1b-8c2d-100000000001",
  "metaObjectKindUid": "14a60875-e241-4e99-b32d-d45b2726d18b",
  "title": "Тестовая операция",
  "name": "test_operation",
  "memo": "Тестовая операция для проверки (с полем Физлицо и тестовой командой).",
  "editMethod": 0,
  "orderByExpression": "",
  "displayExpression": "",
  "listFormUid": null,
  "itemFormUid": null,
  "showMainImage": false,
  "saveHistory": 0,
  "version": 0,
  "isActive": true,
  "header": {
    "uid": "a1b2c3d4-0002-4a1b-8c2d-100000000002",
    "title": "header",
    "name": "header",
    "memo": "",
    "autoClearMethod": 0,
    "columns": [
      {
        "uid": "a1b2c3d4-0003-4a1b-8c2d-100000000003",
        "kind": 0,
        "standardColumnUid": "a39e7b83-e94d-4646-b620-04434fef2f4c",
        "title": "Номер",
        "name": "number",
        "formula": "",
        "itemsSource": "",
        "autoClearMethod": 0,
        "isStandard": true,
        "dataSettings": {
          "dataTypeUid": "b327f82a-ea96-416f-9836-785db28eccac",
          "stringLength": 100,
          "numberDigits": 2,
          "primaryKey": true,
          "required": false,
          "unique": false,
          "defaultValue": null
        },
        "renderSettings": {
          "controlKindUid": "",
          "showInItem": true,
          "showInList": true,
          "listColumnWidth": ""
        },
        "dependencies": []
      },
      {
        "uid": "a1b2c3d4-0004-4a1b-8c2d-100000000004",
        "kind": 0,
        "standardColumnUid": "95d36e42-5d4d-4c26-adc1-1319e860b45e",
        "title": "Удалено",
        "name": "is_deleted",
        "formula": "",
        "itemsSource": "",
        "autoClearMethod": 0,
        "isStandard": true,
        "dataSettings": {
          "dataTypeUid": "4bff64cf-eb01-4933-9f3d-b902336751f4",
          "stringLength": 100,
          "numberDigits": 2,
          "primaryKey": false,
          "required": false,
          "unique": false,
          "defaultValue": null
        },
        "renderSettings": {
          "controlKindUid": "",
          "showInItem": true,
          "showInList": false,
          "listColumnWidth": ""
        },
        "dependencies": []
      },
      {
        "uid": "a1b2c3d4-0005-4a1b-8c2d-100000000005",
        "kind": 0,
        "standardColumnUid": "f244de36-53c9-4e93-a5a2-94abbed91e02",
        "title": "Дата",
        "name": "date",
        "formula": "",
        "itemsSource": "",
        "autoClearMethod": 0,
        "isStandard": true,
        "dataSettings": {
          "dataTypeUid": "9001eafb-efb1-442f-b288-723bb8002b12",
          "stringLength": 100,
          "numberDigits": 2,
          "primaryKey": false,
          "required": true,
          "unique": false,
          "defaultValue": "now"
        },
        "renderSettings": {
          "controlKindUid": "",
          "showInItem": true,
          "showInList": true,
          "listColumnWidth": ""
        },
        "dependencies": []
      },
      {
        "uid": "a1b2c3d4-0006-4a1b-8c2d-100000000006",
        "kind": 0,
        "standardColumnUid": "9cac33f4-6758-4aab-be4a-b00790bdf452",
        "title": "Файлы",
        "name": "is_files",
        "formula": "",
        "itemsSource": "",
        "autoClearMethod": 0,
        "isStandard": true,
        "dataSettings": {
          "dataTypeUid": "4bff64cf-eb01-4933-9f3d-b902336751f4",
          "stringLength": 100,
          "numberDigits": 2,
          "primaryKey": false,
          "required": false,
          "unique": false,
          "defaultValue": null
        },
        "renderSettings": {
          "controlKindUid": "",
          "showInItem": true,
          "showInList": true,
          "listColumnWidth": ""
        },
        "dependencies": []
      },
      {
        "uid": "a1b2c3d4-0007-4a1b-8c2d-100000000007",
        "kind": 0,
        "standardColumnUid": "fee422db-18dc-442a-a8dd-01df76c20a98",
        "title": "Создать записи",
        "name": "create_records",
        "formula": "",
        "itemsSource": "",
        "autoClearMethod": 0,
        "isStandard": true,
        "dataSettings": {
          "dataTypeUid": "4bff64cf-eb01-4933-9f3d-b902336751f4",
          "stringLength": 100,
          "numberDigits": 2,
          "primaryKey": false,
          "required": false,
          "unique": false,
          "defaultValue": "true"
        },
        "renderSettings": {
          "controlKindUid": "",
          "showInItem": true,
          "showInList": true,
          "listColumnWidth": ""
        },
        "dependencies": []
      },
      {
        "uid": "a1b2c3d4-0008-4a1b-8c2d-100000000008",
        "kind": 0,
        "standardColumnUid": null,
        "title": "Физлицо",
        "name": "person",
        "formula": "",
        "itemsSource": "",
        "autoClearMethod": 0,
        "isStandard": false,
        "dataSettings": {
          "dataTypeUid": "7c3e1f92-4d8a-4b2e-9a1c-6f5e2d3b4a01",
          "stringLength": 100,
          "numberDigits": 2,
          "primaryKey": false,
          "required": false,
          "unique": false,
          "defaultValue": null
        },
        "renderSettings": {
          "controlKindUid": "",
          "showInItem": true,
          "showInList": true,
          "listColumnWidth": ""
        },
        "dependencies": []
      }
    ],
    "indexes": [
      {
        "uid": "a1b2c3d4-0009-4a1b-8c2d-100000000009",
        "columns": [
          {
            "columnUid": "a1b2c3d4-0004-4a1b-8c2d-100000000004",
            "direction": 0
          }
        ]
      },
      {
        "uid": "a1b2c3d4-000a-4a1b-8c2d-10000000000a",
        "columns": [
          {
            "columnUid": "a1b2c3d4-0005-4a1b-8c2d-100000000005",
            "direction": 0
          }
        ]
      },
      {
        "uid": "a1b2c3d4-000b-4a1b-8c2d-10000000000b",
        "columns": [
          {
            "columnUid": "a1b2c3d4-0006-4a1b-8c2d-100000000006",
            "direction": 0
          }
        ]
      }
    ]
  },
  "detailTables": [],
  "commands": [
    {
      "uid": "a1b2c3d4-000c-4a1b-8c2d-10000000000c",
      "tableUid": "a1b2c3d4-0002-4a1b-8c2d-100000000002",
      "kind": 0,
      "title": "Тест alert",
      "name": "test_alert",
      "expression": "operation.test_operation.command.test_alert.bjs",
      "memo": "Тестовая команда — показывает alert.",
      "isActive": true,
      "parameters": []
    }
  ],
  "recordsSources": [],
  "recordsSettings": []
}

=== BaSysTeam/BaSYS.Examples.ContractApproval/metadata/catalog/person/catalog.person.json
{
  "$schema": "../../system/schemas/metaObjectStorableSettings.schema.json",
  "uid": "7c3e1f92-4d8a-4b2e-9a1c-6f5e2d3b4a01",
  "metaObjectKindUid": "032d8377-500f-4631-b435-1f7f69046674",
  "title": "Физическое лицо",
  "name": "person",
  "memo": "Справочник физических лиц (ФИО)",
  "editMethod": 0,
  "orderByExpression": "",
  "displayExpression": "",
  "listFormUid": null,
  "itemFormUid": null,
  "showMainImage": false,
  "saveHistory": 0,
  "version": 0,
  "isActive": true,
  "header": {
    "uid": "7c3e1f92-4d8a-4b2e-9a1c-6f5e2d3b4a02",
    "title": "header",
    "name": "header",
    "memo": "",
    "autoClearMethod": 0,
    "columns": [
      {
        "uid": "7c3e1f92-4d8a-4b2e-9a1c-6f5e2d3b4a03",
        "kind": 0,
        "standardColumnUid": "4a7c739c-6012-4e45-bfc0-b78a06db8aec",
        "title": "Id",
        "name": "id",
        "formula": "",
        "itemsSource": "",
        "autoClearMethod": 0,
        "isStandard": true,
        "dataSettings": {
          "dataTypeUid": "b327f82a-ea96-416f-9836-785db28eccac",
          "stringLength": 100,
          "numberDigits": 2,
          "primaryKey": true,
          "required": false,
          "unique": false,
          "defaultValue": null
        },
        "renderSettings": {
          "controlKindUid": "",
          "showInItem": true,
          "showInList": true,
          "listColumnWidth": ""
        },
        "dependencies": []
      },
      {
        "uid": "7c3e1f92-4d8a-4b2e-9a1c-6f5e2d3b4a04",
        "kind": 0,
        "standardColumnUid": "b20fcd24-ba0f-b5b8-7e4d-39628145533e",
        "title": "Uid",
        "name": "uid",
        "formula": "",
        "itemsSource": "",
        "autoClearMethod": 0,
        "isStandard": true,
        "dataSettings": {
          "dataTypeUid": "6fa9c45b-f514-4fea-a480-8e940636a1df",
          "stringLength": 100,
          "numberDigits": 2,
          "primaryKey": false,
          "required": true,
          "unique": true,
          "defaultValue": "new"
        },
        "renderSettings": {
          "controlKindUid": "",
          "showInItem": true,
          "showInList": false,
          "listColumnWidth": ""
        },
        "dependencies": []
      },
      {
        "uid": "7c3e1f92-4d8a-4b2e-9a1c-6f5e2d3b4a05",
        "kind": 0,
        "standardColumnUid": "dc3def1b-bffd-4dc8-b0d5-5d34a57fdcb2",
        "title": "Удалено",
        "name": "is_deleted",
        "formula": "",
        "itemsSource": "",
        "autoClearMethod": 0,
        "isStandard": true,
        "dataSettings": {
          "dataTypeUid": "4bff64cf-eb01-4933-9f3d-b902336751f4",
          "stringLength": 100,
          "numberDigits": 2,
          "primaryKey": false,
          "required": false,
          "unique": false,
          "defaultValue": null
        },
        "renderSettings": {
          "controlKindUid": "",
          "showInItem": true,
          "showInList": false,
          "listColumnWidth": ""
        },
        "dependencies": []
      },
      {
        "uid": "7c3e1f92-4d8a-4b2e-9a1c-6f5e2d3b4a07",
        "kind": 0,
        "standardColumnUid": "349f72d7-ac0f-40cd-b02d-a5b5f7dcd467",
        "title": "Файлы",
        "name": "is_files",
        "formula": "",
        "itemsSource": "",
        "autoClearMethod": 0,
        "isStandard": true,
        "dataSettings": {
          "dataTypeUid": "4bff64cf-eb01-4933-9f3d-b902336751f4",
          "stringLength": 100,
          "numberDigits": 2,
          "primaryKey": false,
          "required": false,
          "unique": false,
          "defaultValue": null
        },
        "renderSettings": {
          "controlKindUid": "",
          "showInItem": true,
          "showInList": true,
          "listColumnWidth": ""
        },
        "dependencies": []
      },
      {
        "uid": "7c3e1f92-4d8a-4b2e-9a1c-6f5e2d3b4a06",
        "kind": 0,
        "standardColumnUid": "e163c0c4-de77-4e58-a468-f3527b573e4a",
        "title": "Заголовок",
        "name": "title",
        "formula": "return [$h.last_name, $h.first_name, $h.middle_name].filter(Boolean).join(' ');",
        "itemsSource": "",
        "autoClearMethod": 0,
        "isStandard": true,
        "dataSettings": {
          "dataTypeUid": "0234c067-7868-46b2-ba8e-e22fae5255cb",
          "stringLength": 150,
          "numberDigits": 2,
          "primaryKey": false,
          "required": true,
          "unique": false,
          "defaultValue": null
        },
        "renderSettings": {
          "controlKindUid": "",
          "showInItem": true,
          "showInList": true,
          "listColumnWidth": ""
        },
        "dependencies": []
      },
      {
        "uid": "7c3e1f92-4d8a-4b2e-9a1c-6f5e2d3b4a08",
        "kind": 0,
        "standardColumnUid": null,
        "title": "Фамилия",
        "name": "last_name",
        "formula": "",
        "itemsSource": "",
        "autoClearMethod": 0,
        "isStandard": false,
        "dataSettings": {
          "dataTypeUid": "0234c067-7868-46b2-ba8e-e22fae5255cb",
          "stringLength": 50,
          "numberDigits": 2,
          "primaryKey": false,
          "required": true,
          "unique": false,
          "defaultValue": null
        },
        "renderSettings": {
          "controlKindUid": "",
          "showInItem": true,
          "showInList": true,
          "listColumnWidth": ""
        },
        "dependencies": [
          {
            "kind": 0,
            "fieldUid": "7c3e1f92-4d8a-4b2e-9a1c-6f5e2d3b4a06",
            "tableUid": "7c3e1f92-4d8a-4b2e-9a1c-6f5e2d3b4a02"
          }
        ]
      },
      {
        "uid": "7c3e1f92-4d8a-4b2e-9a1c-6f5e2d3b4a09",
        "kind": 0,
        "standardColumnUid": null,
        "title": "Имя",
        "name": "first_name",
        "formula": "",
        "itemsSource": "",
        "autoClearMethod": 0,
        "isStandard": false,
        "dataSettings": {
          "dataTypeUid": "0234c067-7868-46b2-ba8e-e22fae5255cb",
          "stringLength": 50,
          "numberDigits": 2,
          "primaryKey": false,
          "required": true,
          "unique": false,
          "defaultValue": null
        },
        "renderSettings": {
          "controlKindUid": "",
          "showInItem": true,
          "showInList": true,
          "listColumnWidth": ""
        },
        "dependencies": [
          {
            "kind": 0,
            "fieldUid": "7c3e1f92-4d8a-4b2e-9a1c-6f5e2d3b4a06",
            "tableUid": "7c3e1f92-4d8a-4b2e-9a1c-6f5e2d3b4a02"
          }
        ]
      },
      {
        "uid": "7c3e1f92-4d8a-4b2e-9a1c-6f5e2d3b4a0a",
        "kind": 0,
        "standardColumnUid": null,
        "title": "Отчество",
        "name": "middle_name",
        "formula": "",
        "itemsSource": "",
        "autoClearMethod": 0,
        "isStandard": false,
        "dataSettings": {
          "dataTypeUid": "0234c067-7868-46b2-ba8e-e22fae5255cb",
          "stringLength": 50,
          "numberDigits": 2,
          "primaryKey": false,
          "required": false,
          "unique": false,
          "defaultValue": null
        },
        "renderSettings": {
          "controlKindUid": "",
          "showInItem": true,
          "showInList": true,
          "listColumnWidth": ""
        },
        "dependencies": [
          {
            "kind": 0,
            "fieldUid": "7c3e1f92-4d8a-4b2e-9a1c-6f5e2d3b4a06",
            "tableUid": "7c3e1f92-4d8a-4b2e-9a1c-6f5e2d3b4a02"
          }
        ]
      }
    ],
    "indexes": [
      {
        "uid": "7c3e1f92-4d8a-4b2e-9a1c-6f5e2d3b4a0b",
        "columns": [
          {
            "columnUid": "7c3e1f92-4d8a-4b2e-9a1c-6f5e2d3b4a05",
            "direction": 0
          }
        ]
      },
      {
        "uid": "7c3e1f92-4d8a-4b2e-9a1c-6f5e2d3b4a0c",
        "columns": [
          {
            "columnUid": "7c3e1f92-4d8a-4b2e-9a1c-6f5e2d3b4a07",
            "direction": 0
          }
        ]
      }
    ]
  },
  "detailTables": [],
  "commands": [],
  "recordsSources": [],
  "recordsSettings": []
}
