=== BaSysTeam/BaSYS.Examples.ContractApproval/metadata/system/schemas/metaObjectStorableSettings.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "MetaObjectStorableSettings",
  "type": "object",
  "properties": {
    "uid": {
      "type": "string",
      "format": "guid"
    },
    "metaObjectKindUid": {
      "type": "string",
      "format": "guid"
    },
    "title": {
      "type": [
        "null",
        "string"
      ]
    },
    "name": {
      "type": [
        "null",
        "string"
      ]
    },
    "memo": {
      "type": [
        "null",
        "string"
      ]
    },
    "editMethod": {
      "$ref": "#/definitions/EditMethods"
    },
    "orderByExpression": {
      "type": [
        "null",
        "string"
      ]
    },
    "displayExpression": {
      "type": [
        "null",
        "string"
      ]
    },
    "listFormUid": {
      "type": [
        "null",
        "string"
      ],
      "format": "guid"
    },
    "itemFormUid": {
      "type": [
        "null",
        "string"
      ],
      "format": "guid"
    },
    "showMainImage": {
      "type": "boolean"
    },
    "saveHistory": {
      "$ref": "#/definitions/SaveHistoryMode"
    },
    "version": {
      "type": "integer",
      "format": "int64"
    },
    "isActive": {
      "type": "boolean"
    },
    "header": {
      "oneOf": [
        {
          "type": "null"
        },
        {
          "$ref": "#/definitions/MetaObjectTable"
        }
      ]
    },
    "detailTables": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "$ref": "#/definitions/MetaObjectTable"
      }
    },
    "commands": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "$ref": "#/definitions/MetaObjectCommand"
      }
    },
    "recordsSources": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "$ref": "#/definitions/RecordsSourceItem"
      }
    },
    "recordsSettings": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "$ref": "#/definitions/MetaObjectRecordsSettingsItem"
      }
    }
  },
  "definitions": {
    "EditMethods": {
      "type": "integer",
      "description": "",
      "x-enumNames": [
        "Page",
        "Modal"
      ],
      "enum": [
        0,
        1
      ]
    },
    "SaveHistoryMode": {
      "type": "integer",
      "description": "",
      "x-enumNames": [
        "Inherit",
        "Disabled",
        "Enabled"
      ],
      "enum": [
        0,
        1,
        2
      ]
    },
    "MetaObjectTable": {
      "type": "object",
      "properties": {
        "uid": {
          "type": "string",
          "format": "guid"
        },
        "title": {
          "type": [
            "null",
            "string"
          ]
        },
        "name": {
          "type": [
            "null",
            "string"
          ]
        },
        "memo": {
          "type": [
            "null",
            "string"
          ]
        },
        "autoClearMethod": {
          "$ref": "#/definitions/AutoClearMethods"
        },
        "columns": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/MetaObjectTableColumn"
          }
        },
        "indexes": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/MetaObjectTableIndex"
          }
        },
        "columnsWithFormulas": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/MetaObjectTableColumn"
          }
        },
        "primaryKey": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "#/definitions/MetaObjectTableColumn"
            }
          ]
        }
      }
    },
    "AutoClearMethods": {
      "type": "integer",
      "description": "",
      "x-enumNames": [
        "None",
        "WhenCopy",
        "WhenCreateFrom",
        "WhenCopyOrCreateFrom"
      ],
      "enum": [
        0,
        1,
        2,
        3
      ]
    },
    "MetaObjectTableColumn": {
      "type": "object",
      "properties": {
        "uid": {
          "type": "string",
          "format": "guid"
        },
        "kind": {
          "$ref": "#/definitions/DataObjectColumnKinds"
        },
        "standardColumnUid": {
          "type": [
            "null",
            "string"
          ],
          "format": "guid"
        },
        "title": {
          "type": [
            "null",
            "string"
          ]
        },
        "name": {
          "type": [
            "null",
            "string"
          ]
        },
        "formula": {
          "type": [
            "null",
            "string"
          ]
        },
        "itemsSource": {
          "type": [
            "null",
            "string"
          ]
        },
        "autoClearMethod": {
          "$ref": "#/definitions/AutoClearMethods"
        },
        "isStandard": {
          "type": "boolean"
        },
        "dataSettings": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "#/definitions/MetaObjectTableColumnDataSettings"
            }
          ]
        },
        "renderSettings": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "#/definitions/MetaObjectTableColumnRenderSettings"
            }
          ]
        },
        "dependencies": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/DependencyInfo"
          }
        }
      }
    },
    "DataObjectColumnKinds": {
      "type": "integer",
      "description": "",
      "x-enumNames": [
        "Stored",
        "Virtual"
      ],
      "enum": [
        0,
        1
      ]
    },
    "MetaObjectTableColumnDataSettings": {
      "type": "object",
      "properties": {
        "dataTypeUid": {
          "type": "string",
          "format": "guid"
        },
        "stringLength": {
          "type": "integer",
          "format": "int32"
        },
        "numberDigits": {
          "type": "integer",
          "format": "int32"
        },
        "primaryKey": {
          "type": "boolean"
        },
        "required": {
          "type": "boolean"
        },
        "unique": {
          "type": "boolean"
        },
        "defaultValue": {
          "type": [
            "null",
            "string"
          ]
        }
      }
    },
    "MetaObjectTableColumnRenderSettings": {
      "type": "object",
      "properties": {
        "controlKindUid": {
          "type": [
            "null",
            "string"
          ]
        },
        "showInItem": {
          "type": "boolean"
        },
        "showInList": {
          "type": "boolean"
        },
        "listColumnWidth": {
          "type": [
            "null",
            "string"
          ]
        }
      }
    },
    "DependencyInfo": {
      "type": "object",
      "properties": {
        "kind": {
          "$ref": "#/definitions/DependencyKinds"
        },
        "fieldUid": {
          "type": "string",
          "format": "guid"
        },
        "tableUid": {
          "type": "string",
          "format": "guid"
        }
      }
    },
    "DependencyKinds": {
      "type": "integer",
      "description": "",
      "x-enumNames": [
        "HeaderField",
        "RowField",
        "Table"
      ],
      "enum": [
        0,
        1,
        2
      ]
    },
    "MetaObjectTableIndex": {
      "type": "object",
      "properties": {
        "uid": {
          "type": "string",
          "format": "guid"
        },
        "columns": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/MetaObjectTableIndexColumn"
          }
        }
      }
    },
    "MetaObjectTableIndexColumn": {
      "type": "object",
      "properties": {
        "columnUid": {
          "type": "string",
          "format": "guid"
        },
        "direction": {
          "$ref": "#/definitions/IndexDirections"
        }
      }
    },
    "IndexDirections": {
      "type": "integer",
      "description": "",
      "x-enumNames": [
        "Descending",
        "Ascending"
      ],
      "enum": [
        0,
        1
      ]
    },
    "MetaObjectCommand": {
      "type": "object",
      "properties": {
        "uid": {
          "type": "string",
          "format": "guid"
        },
        "tableUid": {
          "type": "string",
          "format": "guid"
        },
        "kind": {
          "$ref": "#/definitions/MetaObjectCommandKinds"
        },
        "title": {
          "type": [
            "null",
            "string"
          ]
        },
        "name": {
          "type": [
            "null",
            "string"
          ]
        },
        "expression": {
          "type": [
            "null",
            "string"
          ],
          "description": "JavaScript expression for this command. In export packages the value is a relative file reference (e.g. 'Catalog.Customer.command.fill_defaults.bjs') pointing to a companion .bjs file; the import pipeline resolves it back to inline code automatically.",
          "x-example": "Catalog.Customer.command.fill_defaults.bjs"
        },
        "memo": {
          "type": [
            "null",
            "string"
          ]
        },
        "isActive": {
          "type": "boolean"
        },
        "parameters": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/MetaObjectCommandParameter"
          }
        }
      }
    },
    "MetaObjectCommandKinds": {
      "type": "integer",
      "description": "",
      "x-enumNames": [
        "Custom",
        "Fill",
        "PickUp"
      ],
      "enum": [
        0,
        1,
        2
      ]
    },
    "MetaObjectCommandParameter": {
      "type": "object",
      "properties": {
        "name": {
          "type": [
            "null",
            "string"
          ]
        },
        "value": {
          "type": [
            "null",
            "string"
          ]
        },
        "dbType": {
          "$ref": "#/definitions/DbType"
        }
      }
    },
    "DbType": {
      "type": "integer",
      "description": "",
      "x-enumNames": [
        "AnsiString",
        "Binary",
        "Byte",
        "Boolean",
        "Currency",
        "Date",
        "DateTime",
        "Decimal",
        "Double",
        "Guid",
        "Int16",
        "Int32",
        "Int64",
        "Object",
        "SByte",
        "Single",
        "String",
        "Time",
        "UInt16",
        "UInt32",
        "UInt64",
        "VarNumeric",
        "AnsiStringFixedLength",
        "StringFixedLength",
        "Xml",
        "DateTime2",
        "DateTimeOffset"
      ],
      "enum": [
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20,
        21,
        22,
        23,
        25,
        26,
        27
      ]
    },
    "RecordsSourceItem": {
      "type": "object",
      "properties": {
        "uid": {
          "type": "string",
          "format": "guid"
        },
        "title": {
          "type": [
            "null",
            "string"
          ]
        },
        "expression": {
          "type": [
            "null",
            "string"
          ],
          "description": "JavaScript expression for this records source. In export packages the value is a relative file reference (e.g. 'Catalog.Customer.records_source.main.bjs') pointing to a companion .bjs file; the import pipeline resolves it back to inline code automatically.",
          "x-example": "Catalog.Customer.records_source.main.bjs"
        }
      }
    },
    "MetaObjectRecordsSettingsItem": {
      "type": "object",
      "properties": {
        "destinationMetaObjectUid": {
          "type": "string",
          "format": "guid"
        },
        "rows": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/MetaObjectRecordsSettingsRow"
          }
        }
      }
    },
    "MetaObjectRecordsSettingsRow": {
      "type": "object",
      "properties": {
        "uid": {
          "type": "string",
          "format": "guid"
        },
        "sourceUid": {
          "type": "string",
          "format": "guid"
        },
        "direction": {
          "$ref": "#/definitions/RegisterRecordDirections"
        },
        "condition": {
          "type": [
            "null",
            "string"
          ]
        },
        "columns": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/MetaObjectRecordsSettingsColumn"
          }
        }
      }
    },
    "RegisterRecordDirections": {
      "type": "integer",
      "description": "",
      "x-enumNames": [
        "Plus",
        "Minus"
      ],
      "enum": [
        0,
        1
      ]
    },
    "MetaObjectRecordsSettingsColumn": {
      "type": "object",
      "properties": {
        "destinationColumnUid": {
          "type": "string",
          "format": "guid"
        },
        "expression": {
          "type": [
            "null",
            "string"
          ]
        }
      }
    }
  }
}

=== BaSysTeam/BaSYS.Examples.ContractApproval/enum/contract_type/enum.contract_type.json
{
  "$schema": "../../system/schemas/metaObjectStorableSettings.schema.json",
  "uid": "b8c9d0e1-f2a3-4b5c-8d6e-7f8a9b0c1d2e",
  "metaObjectKindUid": "5449a8ad-9359-41b2-8ff2-3f415eb4da76",
  "title": "Тип договора",
  "name": "contract_type",
  "memo": "Тип договора (типовой / форма поставщика и т.п.). Параллельная классификация к виду договора.",
  "editMethod": 0,
  "orderByExpression": "",
  "displayExpression": "",
  "listFormUid": null,
  "itemFormUid": null,
  "showMainImage": false,
  "version": 0,
  "isActive": true,
  "header": {
    "uid": "c9d0e1f2-a3b4-4c5d-9e6f-7a8b9c0d1e2f",
    "title": "header",
    "name": "header",
    "memo": "",
    "autoClearMethod": 0,
    "columns": [
      {
        "uid": "d0e1f2a3-b4c5-4d5e-9f6a-7b8c9d0e1f20",
        "kind": 0,
        "standardColumnUid": "3cceebad-7d5a-4943-a102-6267e22227a8",
        "title": "Имя",
        "name": "name",
        "formula": "",
        "itemsSource": "",
        "autoClearMethod": 0,
        "isStandard": true,
        "dataSettings": {
          "dataTypeUid": "0234c067-7868-46b2-ba8e-e22fae5255cb",
          "stringLength": 20,
          "numberDigits": 2,
          "primaryKey": true,
          "required": false,
          "unique": false,
          "defaultValue": null
        },
        "renderSettings": {
          "controlKindUid": "",
          "showInItem": true,
          "showInList": true,
          "listColumnWidth": ""
        },
        "dependencies": []
      },
      {
        "uid": "e1f2a3b4-c5d6-4e5f-906b-7c8d9e0f1a21",
        "kind": 0,
        "standardColumnUid": "1e0063d0-288d-494a-8761-1185300d571d",
        "title": "Удалено",
        "name": "is_deleted",
        "formula": "",
        "itemsSource": "",
        "autoClearMethod": 0,
        "isStandard": true,
        "dataSettings": {
          "dataTypeUid": "4bff64cf-eb01-4933-9f3d-b902336751f4",
          "stringLength": 100,
          "numberDigits": 2,
          "primaryKey": false,
          "required": false,
          "unique": false,
          "defaultValue": null
        },
        "renderSettings": {
          "controlKindUid": "",
          "showInItem": true,
          "showInList": false,
          "listColumnWidth": ""
        },
        "dependencies": []
      },
      {
        "uid": "f2a3b4c5-d6e7-4f50-916c-7d8e9f0a1b22",
        "kind": 0,
        "standardColumnUid": "e647fb57-470e-4547-9a94-2be0f3d0985e",
        "title": "Код",
        "name": "code",
        "formula": "",
        "itemsSource": "",
        "autoClearMethod": 0,
        "isStandard": true,
        "dataSettings": {
          "dataTypeUid": "0234c067-7868-46b2-ba8e-e22fae5255cb",
          "stringLength": 3,
          "numberDigits": 2,
          "primaryKey": false,
          "required": true,
          "unique": true,
          "defaultValue": null
        },
        "renderSettings": {
          "controlKindUid": "",
          "showInItem": true,
          "showInList": true,
          "listColumnWidth": ""
        },
        "dependencies": []
      },
      {
        "uid": "a3b4c5d6-e7f8-4051-826d-7e8f9a0b1c23",
        "kind": 0,
        "standardColumnUid": "91a26ae4-5723-4109-8322-7e4e59129239",
        "title": "Заголовок",
        "name": "title",
        "formula": "",
        "itemsSource": "",
        "autoClearMethod": 0,
        "isStandard": true,
        "dataSettings": {
          "dataTypeUid": "0234c067-7868-46b2-ba8e-e22fae5255cb",
          "stringLength": 100,
          "numberDigits": 2,
          "primaryKey": false,
          "required": true,
          "unique": false,
          "defaultValue": null
        },
        "renderSettings": {
          "controlKindUid": "",
          "showInItem": true,
          "showInList": true,
          "listColumnWidth": ""
        },
        "dependencies": []
      }
    ],
    "indexes": [
      {
        "uid": "b4c5d6e7-f809-4152-836e-7f809a1b2c34",
        "columns": [
          {
            "columnUid": "e1f2a3b4-c5d6-4e5f-906b-7c8d9e0f1a21",
            "direction": 0
          }
        ]
      },
      {
        "uid": "c5d6e7f8-091a-4253-846f-8091a2b3c4d5",
        "columns": [
          {
            "columnUid": "f2a3b4c5-d6e7-4f50-916c-7d8e9f0a1b22",
            "direction": 0
          }
        ]
      }
    ]
  },
  "detailTables": [],
  "commands": [],
  "recordsSources": [],
  "recordsSettings": []
}

=== BaSysTeam/BaSYS.Examples.ContractApproval/metadata/enum/contract_status/enum.contract_status.json
{
  "$schema": "../../system/schemas/metaObjectStorableSettings.schema.json",
  "uid": "a3f1b8e2-7c4d-4a5b-9e6f-1d2c3b4a5e6f",
  "metaObjectKindUid": "5449a8ad-9359-41b2-8ff2-3f415eb4da76",
  "title": "Статус договора",
  "name": "contract_status",
  "memo": "Возможные статусы договора в процессе согласования и исполнения",
  "editMethod": 0,
  "orderByExpression": "",
  "displayExpression": "",
  "listFormUid": null,
  "itemFormUid": null,
  "showMainImage": false,
  "saveHistory": 0,
  "version": 0,
  "isActive": true,
  "header": {
    "uid": "b4e2c9f3-8d5e-4b6c-af7a-2e3d4c5b6f7a",
    "title": "header",
    "name": "header",
    "memo": "",
    "autoClearMethod": 0,
    "columns": [
      {
        "uid": "c5f3dae4-9e6f-4c7d-bb8b-3f4e5d6c7a8b",
        "kind": 0,
        "standardColumnUid": "3cceebad-7d5a-4943-a102-6267e22227a8",
        "title": "Имя",
        "name": "name",
        "formula": "",
        "itemsSource": "",
        "autoClearMethod": 0,
        "isStandard": true,
        "dataSettings": {
          "dataTypeUid": "0234c067-7868-46b2-ba8e-e22fae5255cb",
          "stringLength": 20,
          "numberDigits": 2,
          "primaryKey": true,
          "required": false,
          "unique": false,
          "defaultValue": null
        },
        "renderSettings": {
          "controlKindUid": "",
          "showInItem": true,
          "showInList": true,
          "listColumnWidth": ""
        },
        "dependencies": []
      },
      {
        "uid": "d6e4ebf5-af70-4d8e-9c9c-4f5d6e7a8b9c",
        "kind": 0,
        "standardColumnUid": "1e0063d0-288d-494a-8761-1185300d571d",
        "title": "Удалено",
        "name": "is_deleted",
        "formula": "",
        "itemsSource": "",
        "autoClearMethod": 0,
        "isStandard": true,
        "dataSettings": {
          "dataTypeUid": "4bff64cf-eb01-4933-9f3d-b902336751f4",
          "stringLength": 100,
          "numberDigits": 2,
          "primaryKey": false,
          "required": false,
          "unique": false,
          "defaultValue": null
        },
        "renderSettings": {
          "controlKindUid": "",
          "showInItem": true,
          "showInList": false,
          "listColumnWidth": ""
        },
        "dependencies": []
      },
      {
        "uid": "e7f5fc06-bf81-4e9f-9dad-5f6e7a8b9c0d",
        "kind": 0,
        "standardColumnUid": "e647fb57-470e-4547-9a94-2be0f3d0985e",
        "title": "Код",
        "name": "code",
        "formula": "",
        "itemsSource": "",
        "autoClearMethod": 0,
        "isStandard": true,
        "dataSettings": {
          "dataTypeUid": "0234c067-7868-46b2-ba8e-e22fae5255cb",
          "stringLength": 3,
          "numberDigits": 2,
          "primaryKey": false,
          "required": true,
          "unique": true,
          "defaultValue": null
        },
        "renderSettings": {
          "controlKindUid": "",
          "showInItem": true,
          "showInList": true,
          "listColumnWidth": ""
        },
        "dependencies": []
      },
      {
        "uid": "f8e6cd17-c092-4faf-aebe-6e7a8b9c0d1e",
        "kind": 0,
        "standardColumnUid": "91a26ae4-5723-4109-8322-7e4e59129239",
        "title": "Заголовок",
        "name": "title",
        "formula": "",
        "itemsSource": "",
        "autoClearMethod": 0,
        "isStandard": true,
        "dataSettings": {
          "dataTypeUid": "0234c067-7868-46b2-ba8e-e22fae5255cb",
          "stringLength": 100,
          "numberDigits": 2,
          "primaryKey": false,
          "required": true,
          "unique": false,
          "defaultValue": null
        },
        "renderSettings": {
          "controlKindUid": "",
          "showInItem": true,
          "showInList": true,
          "listColumnWidth": ""
        },
        "dependencies": []
      }
    ],
    "indexes": [
      {
        "uid": "a9f7de28-d1a3-4ab0-aacf-7a8b9c0d1e2f",
        "columns": [
          {
            "columnUid": "d6e4ebf5-af70-4d8e-9c9c-4f5d6e7a8b9c",
            "direction": 0
          }
        ]
      },
      {
        "uid": "bae8ef39-e2b4-4bc1-bbe0-8b9c0d1e2f3a",
        "columns": [
          {
            "columnUid": "e7f5fc06-bf81-4e9f-9dad-5f6e7a8b9c0d",
            "direction": 0
          }
        ]
      }
    ]
  },
  "detailTables": [],
  "commands": [],
  "recordsSources": [],
  "recordsSettings": []
}
