=== BaSysTeam/BaSYS.Examples.ContractApproval/metadata/system/schemas/workflowSettings.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "WorkflowSettingsDto",
  "type": "object",
  "properties": {
    "uid": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "memo": {
      "type": "string"
    },
    "isActive": {
      "type": "boolean"
    },
    "version": {
      "type": "integer",
      "format": "int64"
    },
    "parameters": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/WorkflowParameterDefinition"
      }
    },
    "steps": {
      "type": "array",
      "items": {
        "oneOf": [
          {
            "$ref": "#/definitions/SleepStepSettingsDto"
          },
          {
            "$ref": "#/definitions/MessageStepSettingsDto"
          },
          {
            "$ref": "#/definitions/HttpConnectorStepSettingsDto"
          },
          {
            "$ref": "#/definitions/JavaScriptStepSettingsDto"
          },
          {
            "$ref": "#/definitions/IfStepSettingsDto"
          },
          {
            "$ref": "#/definitions/DataObjectLoaderStepSettingsDto"
          },
          {
            "$ref": "#/definitions/IteratorStepSettingsDto"
          },
          {
            "$ref": "#/definitions/IteratorStopStepSettingsDto"
          },
          {
            "$ref": "#/definitions/ReadFileStepSettingsDto"
          },
          {
            "$ref": "#/definitions/ExcelMappingStepSettingsDto"
          },
          {
            "$ref": "#/definitions/SmtpSendStepSettingsDto"
          }
        ]
      }
    }
  },
  "definitions": {
    "WorkflowParameterDefinition": {
      "type": "object",
      "properties": {
        "uid": {
          "type": "string",
          "format": "guid"
        },
        "name": {
          "type": [
            "null",
            "string"
          ]
        },
        "dataType": {
          "type": [
            "null",
            "string"
          ]
        },
        "defaultValue": {
          "type": [
            "null",
            "string"
          ]
        },
        "required": {
          "type": "boolean"
        },
        "memo": {
          "type": [
            "null",
            "string"
          ]
        }
      }
    },
    "SleepStepSettingsDto": {
      "type": "object",
      "required": [
        "uid",
        "kindUid",
        "kindName"
      ],
      "properties": {
        "uid": {
          "type": "string"
        },
        "previousStepUid": {
          "type": "string"
        },
        "kindUid": {
          "type": "string",
          "enum": [
            "2a5aca6d-2c41-4bd2-9e03-b35df7dab23e"
          ]
        },
        "kindName": {
          "type": "string",
          "enum": [
            "sleep"
          ]
        },
        "title": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "memo": {
          "type": "string"
        },
        "isActive": {
          "type": "boolean"
        },
        "delay": {
          "type": "string"
        }
      }
    },
    "MessageStepSettingsDto": {
      "type": "object",
      "required": [
        "uid",
        "kindUid",
        "kindName"
      ],
      "properties": {
        "uid": {
          "type": "string"
        },
        "previousStepUid": {
          "type": "string"
        },
        "kindUid": {
          "type": "string",
          "enum": [
            "e192c288-154e-4778-b92c-64da27279796"
          ]
        },
        "kindName": {
          "type": "string",
          "enum": [
            "message"
          ]
        },
        "title": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "memo": {
          "type": "string"
        },
        "isActive": {
          "type": "boolean"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "HttpConnectorStepSettingsDto": {
      "type": "object",
      "required": [
        "uid",
        "kindUid",
        "kindName"
      ],
      "properties": {
        "uid": {
          "type": "string"
        },
        "previousStepUid": {
          "type": "string"
        },
        "kindUid": {
          "type": "string",
          "enum": [
            "bb368829-007d-4b8e-87ce-1dadee75c7c3"
          ]
        },
        "kindName": {
          "type": "string",
          "enum": [
            "http_connector"
          ]
        },
        "title": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "memo": {
          "type": "string"
        },
        "isActive": {
          "type": "boolean"
        },
        "url": {
          "type": "string"
        },
        "bodyKind": {
          "$ref": "#/definitions/HttpBodyKinds"
        },
        "bodyEncoding": {
          "$ref": "#/definitions/HttpBodyEncoding"
        },
        "body": {
          "type": "string"
        },
        "method": {
          "$ref": "#/definitions/HttpMethods"
        },
        "timeout": {
          "type": "integer",
          "format": "int32"
        },
        "logResponse": {
          "type": "boolean"
        },
        "autoParse": {
          "type": "boolean"
        },
        "bypassSslCertificate": {
          "type": "boolean"
        },
        "returnResponseInfo": {
          "type": "boolean"
        },
        "allowSetCookieFromHeaders": {
          "type": "boolean"
        },
        "headers": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/NameValueDescriptionRow"
          }
        },
        "parameters": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/NameValueDescriptionRow"
          }
        },
        "formData": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/NameValueDescriptionRow"
          }
        }
      }
    },
    "HttpBodyKinds": {
      "type": "integer",
      "description": "",
      "x-enumNames": [
        "Undefined",
        "JSON",
        "FormData",
        "XWWWFormUrlEncoded",
        "XML"
      ],
      "enum": [
        0,
        1,
        2,
        3,
        4
      ]
    },
    "HttpBodyEncoding": {
      "type": "integer",
      "description": "",
      "x-enumNames": [
        "UTF8",
        "None"
      ],
      "enum": [
        0,
        -1
      ]
    },
    "HttpMethods": {
      "type": "integer",
      "description": "",
      "x-enumNames": [
        "Get",
        "Post",
        "Put",
        "Patch",
        "Delete"
      ],
      "enum": [
        0,
        1,
        2,
        3,
        4
      ]
    },
    "NameValueDescriptionRow": {
      "type": "object",
      "properties": {
        "uid": {
          "type": "string",
          "format": "guid"
        },
        "name": {
          "type": [
            "null",
            "string"
          ]
        },
        "value": {
          "type": [
            "null",
            "string"
          ]
        },
        "description": {
          "type": [
            "null",
            "string"
          ]
        }
      }
    },
    "JavaScriptStepSettingsDto": {
      "type": "object",
      "required": [
        "uid",
        "kindUid",
        "kindName"
      ],
      "properties": {
        "uid": {
          "type": "string"
        },
        "previousStepUid": {
          "type": "string"
        },
        "kindUid": {
          "type": "string",
          "enum": [
            "dff616ce-0f40-4e44-a82b-14aa5ee2e4d6"
          ]
        },
        "kindName": {
          "type": "string",
          "enum": [
            "java_script"
          ]
        },
        "title": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "memo": {
          "type": "string"
        },
        "isActive": {
          "type": "boolean"
        },
        "expression": {
          "type": "string",
          "description": "JavaScript expression for this step. In export packages the value is a relative file reference (e.g. 'workflow.my_process.step.calculate.bjs') pointing to a companion .bjs file; the import pipeline resolves it back to inline code automatically.",
          "x-example": "workflow.my_process.step.calculate.bjs"
        }
      }
    },
    "IfStepSettingsDto": {
      "type": "object",
      "required": [
        "uid",
        "kindUid",
        "kindName"
      ],
      "properties": {
        "uid": {
          "type": "string"
        },
        "previousStepUid": {
          "type": "string"
        },
        "kindUid": {
          "type": "string",
          "enum": [
            "9a3a0dc1-b4ed-4679-9f72-0667b7dcfa53"
          ]
        },
        "kindName": {
          "type": "string",
          "enum": [
            "if"
          ]
        },
        "title": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "memo": {
          "type": "string"
        },
        "isActive": {
          "type": "boolean"
        },
        "condition": {
          "type": "string"
        },
        "trueStepUid": {
          "type": "string"
        },
        "falseStepUid": {
          "type": "string"
        }
      }
    },
    "DataObjectLoaderStepSettingsDto": {
      "type": "object",
      "required": [
        "uid",
        "kindUid",
        "kindName"
      ],
      "properties": {
        "uid": {
          "type": "string"
        },
        "previousStepUid": {
          "type": "string"
        },
        "kindUid": {
          "type": "string",
          "enum": [
            "a7edd0be-6f12-4fac-b88a-4f83acc7dacb"
          ]
        },
        "kindName": {
          "type": "string",
          "enum": [
            "data_object_loader"
          ]
        },
        "title": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "memo": {
          "type": "string"
        },
        "isActive": {
          "type": "boolean"
        },
        "metaObjectKindUid": {
          "type": "string",
          "format": "guid"
        },
        "metaObjectUid": {
          "type": "string",
          "format": "guid"
        },
        "saveRegime": {
          "$ref": "#/definitions/SaveRegimes"
        },
        "searchBy": {
          "type": "string"
        },
        "sourcePath": {
          "type": "string"
        },
        "condition": {
          "type": "string"
        },
        "createRecords": {
          "type": "boolean"
        },
        "skipHistory": {
          "type": "boolean"
        },
        "headerMapping": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/FieldMappingRow"
          }
        },
        "tableMapping": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/DetailsTableLoadSettings"
          }
        }
      }
    },
    "SaveRegimes": {
      "type": "integer",
      "description": "",
      "x-enumNames": [
        "CreateUpdate",
        "Create",
        "Update"
      ],
      "enum": [
        0,
        1,
        2
      ]
    },
    "FieldMappingRow": {
      "type": "object",
      "properties": {
        "uid": {
          "type": "string",
          "format": "guid"
        },
        "sourceFieldName": {
          "type": [
            "null",
            "string"
          ]
        },
        "destinationFieldName": {
          "type": [
            "null",
            "string"
          ]
        },
        "defaultValue": {
          "type": [
            "null",
            "string"
          ]
        },
        "searchBy": {
          "type": [
            "null",
            "string"
          ]
        },
        "dataTypeUid": {
          "type": "string",
          "format": "guid"
        },
        "createIfNotExist": {
          "type": "boolean"
        }
      }
    },
    "DetailsTableLoadSettings": {
      "type": "object",
      "properties": {
        "tableUid": {
          "type": "string",
          "format": "guid"
        },
        "sourcePath": {
          "type": [
            "null",
            "string"
          ]
        },
        "mapping": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/FieldMappingRow"
          }
        }
      }
    },
    "IteratorStepSettingsDto": {
      "type": "object",
      "required": [
        "uid",
        "kindUid",
        "kindName"
      ],
      "properties": {
        "uid": {
          "type": "string"
        },
        "previousStepUid": {
          "type": "string"
        },
        "kindUid": {
          "type": "string",
          "enum": [
            "07e698af-d11b-454b-a7f4-577a0439e92c"
          ]
        },
        "kindName": {
          "type": "string",
          "enum": [
            "iterator"
          ]
        },
        "title": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "memo": {
          "type": "string"
        },
        "isActive": {
          "type": "boolean"
        },
        "sourcePath": {
          "type": "string"
        },
        "itemName": {
          "type": "string"
        }
      }
    },
    "IteratorStopStepSettingsDto": {
      "type": "object",
      "required": [
        "uid",
        "kindUid",
        "kindName"
      ],
      "properties": {
        "uid": {
          "type": "string"
        },
        "previousStepUid": {
          "type": "string"
        },
        "kindUid": {
          "type": "string",
          "enum": [
            "ac090927-e291-4421-b9aa-351b8fa51770"
          ]
        },
        "kindName": {
          "type": "string",
          "enum": [
            "iterator_stop"
          ]
        },
        "title": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "memo": {
          "type": "string"
        },
        "isActive": {
          "type": "boolean"
        }
      }
    },
    "ReadFileStepSettingsDto": {
      "type": "object",
      "required": [
        "uid",
        "kindUid",
        "kindName"
      ],
      "properties": {
        "uid": {
          "type": "string"
        },
        "previousStepUid": {
          "type": "string"
        },
        "kindUid": {
          "type": "string",
          "enum": [
            "800c9045-1c1c-46d0-a15f-968a43220d1a"
          ]
        },
        "kindName": {
          "type": "string",
          "enum": [
            "read_file"
          ]
        },
        "title": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "memo": {
          "type": "string"
        },
        "isActive": {
          "type": "boolean"
        },
        "regime": {
          "$ref": "#/definitions/WorkflowReadFileRegimes"
        },
        "outputFormat": {
          "$ref": "#/definitions/ReadFileOutputFormats"
        },
        "attachedFileUidExpression": {
          "type": "string"
        }
      }
    },
    "WorkflowReadFileRegimes": {
      "type": "integer",
      "description": "",
      "x-enumNames": [
        "Interactive",
        "AttachedFile"
      ],
      "enum": [
        0,
        1
      ]
    },
    "ReadFileOutputFormats": {
      "type": "integer",
      "description": "",
      "x-enumNames": [
        "Binary",
        "Text"
      ],
      "enum": [
        0,
        1
      ]
    },
    "ExcelMappingStepSettingsDto": {
      "type": "object",
      "required": [
        "uid",
        "kindUid",
        "kindName"
      ],
      "properties": {
        "uid": {
          "type": "string"
        },
        "previousStepUid": {
          "type": "string"
        },
        "kindUid": {
          "type": "string",
          "enum": [
            "762db492-58b2-4e7e-86ca-0b80b0e3aaae"
          ]
        },
        "kindName": {
          "type": "string",
          "enum": [
            "excel_mapping"
          ]
        },
        "title": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "memo": {
          "type": "string"
        },
        "isActive": {
          "type": "boolean"
        },
        "sourcePath": {
          "type": "string"
        },
        "sheetName": {
          "type": "string"
        },
        "startRow": {
          "type": "integer",
          "format": "int32"
        },
        "endRow": {
          "type": "integer",
          "format": "int32"
        },
        "mapping": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ExcelMappingRow"
          }
        }
      }
    },
    "ExcelMappingRow": {
      "type": "object",
      "properties": {
        "uid": {
          "type": "string",
          "format": "guid"
        },
        "sourceFieldName": {
          "type": [
            "null",
            "string"
          ]
        },
        "destinationFieldName": {
          "type": [
            "null",
            "string"
          ]
        },
        "dataTypeUid": {
          "type": "string",
          "format": "guid"
        }
      }
    },
    "SmtpSendStepSettingsDto": {
      "type": "object",
      "required": [
        "uid",
        "kindUid",
        "kindName"
      ],
      "properties": {
        "uid": {
          "type": "string"
        },
        "previousStepUid": {
          "type": "string"
        },
        "kindUid": {
          "type": "string",
          "enum": [
            "df48f1ed-2bcf-4b1d-b45c-1305b55ce1f6"
          ]
        },
        "kindName": {
          "type": "string",
          "enum": [
            "smtp_send"
          ]
        },
        "title": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "memo": {
          "type": "string"
        },
        "isActive": {
          "type": "boolean"
        },
        "host": {
          "type": "string"
        },
        "user": {
          "type": "string"
        },
        "password": {
          "type": "string"
        },
        "port": {
          "type": "string"
        },
        "timeoutSeconds": {
          "type": "integer",
          "format": "int32"
        },
        "enableSsl": {
          "type": "boolean"
        },
        "from": {
          "type": "string"
        },
        "to": {
          "type": "string"
        },
        "cc": {
          "type": "string"
        },
        "bcc": {
          "type": "string"
        },
        "subject": {
          "type": "string"
        },
        "body": {
          "type": "string"
        },
        "isBodyHtml": {
          "type": "boolean"
        }
      }
    }
  }
}

=== BaSysTeam/BaSYS.Examples.ContractApproval/metadata/workflow/fill_contract_type/workflow.fill_contract_type.json
{
  "$schema": "../../system/schemas/workflowSettings.schema.json",
  "uid": "d4e5f6a7-b8c9-4d0e-9f1a-2b3c4d5e6f70",
  "name": "fill_contract_type",
  "title": "01.003 Заполнение типов договоров",
  "memo": "Первоначальное заполнение перечисления contract_type стандартными значениями.",
  "isActive": true,
  "version": 2,
  "parameters": [],
  "steps": [
    {
      "expression": "workflow.fill_contract_type.step.data.bjs",
      "uid": "e5f6a7b8-c9d0-4e1f-9a2b-3c4d5e6f7081",
      "previousStepUid": "",
      "kindUid": "dff616ce-0f40-4e44-a82b-14aa5ee2e4d6",
      "kindName": "java_script",
      "title": "Данные",
      "name": "data",
      "memo": "Подготовка DataTable со значениями типов договоров.",
      "isActive": true
    },
    {
      "metaObjectKindUid": "5449a8ad-9359-41b2-8ff2-3f415eb4da76",
      "metaObjectUid": "b8c9d0e1-f2a3-4b5c-8d6e-7f8a9b0c1d2e",
      "saveRegime": 1,
      "searchBy": "name",
      "sourcePath": "data",
      "condition": "",
      "createRecords": false,
      "skipHistory": false,
      "headerMapping": [
        {
          "uid": "a7b8c9d0-e1f2-4a3b-9c4d-5e6f708192a3",
          "sourceFieldName": "name",
          "destinationFieldName": "name",
          "defaultValue": "",
          "searchBy": "",
          "dataTypeUid": "0234c067-7868-46b2-ba8e-e22fae5255cb",
          "createIfNotExist": false
        },
        {
          "uid": "b8c9d0e1-f2a3-4b4c-9d5e-6f708192a3b4",
          "sourceFieldName": "code",
          "destinationFieldName": "code",
          "defaultValue": "",
          "searchBy": "",
          "dataTypeUid": "0234c067-7868-46b2-ba8e-e22fae5255cb",
          "createIfNotExist": false
        },
        {
          "uid": "c9d0e1f2-a3b4-4c5d-9e6f-708192a3b4c5",
          "sourceFieldName": "title",
          "destinationFieldName": "title",
          "defaultValue": "",
          "searchBy": "",
          "dataTypeUid": "0234c067-7868-46b2-ba8e-e22fae5255cb",
          "createIfNotExist": false
        }
      ],
      "tableMapping": [],
      "uid": "f6a7b8c9-d0e1-4f2a-9b3c-4d5e6f708192",
      "previousStepUid": "e5f6a7b8-c9d0-4e1f-9a2b-3c4d5e6f7081",
      "kindUid": "a7edd0be-6f12-4fac-b88a-4f83acc7dacb",
      "kindName": "data_object_loader",
      "title": "Загрузка данных",
      "name": "load",
      "memo": "Создание значений перечисления contract_type. Режим Create, чтобы не задублировать уже существующие записи.",
      "isActive": true
    }
  ]
}

=== BaSysTeam/BaSYS.Examples.ContractApproval/metadata/workflow/fill_contract_priority/workflow.fill_contract_priority.json
{
  "$schema": "../../system/schemas/workflowSettings.schema.json",
  "uid": "3f9c1a72-6b4d-4e18-9a2f-8c5d7e1b0a34",
  "name": "fill_contract_priority",
  "title": "01.005 Заполнение приоритетов договоров",
  "memo": "Первоначальное заполнение перечисления contract_priority стандартными значениями.",
  "isActive": true,
  "version": 2,
  "parameters": [],
  "steps": [
    {
      "expression": "workflow.fill_contract_priority.step.data.bjs",
      "uid": "a4b8c1d2-3e5f-4a67-8b9c-1d2e3f4a5b60",
      "previousStepUid": "",
      "kindUid": "dff616ce-0f40-4e44-a82b-14aa5ee2e4d6",
      "kindName": "java_script",
      "title": "Данные",
      "name": "data",
      "memo": "Подготовка DataTable со значениями приоритетов договоров.",
      "isActive": true
    },
    {
      "metaObjectKindUid": "5449a8ad-9359-41b2-8ff2-3f415eb4da76",
      "metaObjectUid": "8aeea012-aba9-426a-a6a2-b02f9d76eab6",
      "saveRegime": 1,
      "searchBy": "name",
      "sourcePath": "data",
      "condition": "",
      "createRecords": false,
      "skipHistory": false,
      "headerMapping": [
        {
          "uid": "b5c9d2e3-4f60-4b78-9c0d-2e3f4a5b6c71",
          "sourceFieldName": "name",
          "destinationFieldName": "name",
          "defaultValue": "",
          "searchBy": "",
          "dataTypeUid": "0234c067-7868-46b2-ba8e-e22fae5255cb",
          "createIfNotExist": false
        },
        {
          "uid": "c6d0e3f4-5a71-4c89-9d1e-3f4a5b6c7d82",
          "sourceFieldName": "code",
          "destinationFieldName": "code",
          "defaultValue": "",
          "searchBy": "",
          "dataTypeUid": "0234c067-7868-46b2-ba8e-e22fae5255cb",
          "createIfNotExist": false
        },
        {
          "uid": "d7e1f4a5-6b82-4d90-9e2f-4a5b6c7d8e93",
          "sourceFieldName": "title",
          "destinationFieldName": "title",
          "defaultValue": "",
          "searchBy": "",
          "dataTypeUid": "0234c067-7868-46b2-ba8e-e22fae5255cb",
          "createIfNotExist": false
        }
      ],
      "tableMapping": [],
      "uid": "e8f2a5b6-7c93-4ea1-9f30-5b6c7d8e9f04",
      "previousStepUid": "a4b8c1d2-3e5f-4a67-8b9c-1d2e3f4a5b60",
      "kindUid": "a7edd0be-6f12-4fac-b88a-4f83acc7dacb",
      "kindName": "data_object_loader",
      "title": "Загрузка данных",
      "name": "load",
      "memo": "Создание значений перечисления contract_priority. Режим Create, чтобы не задублировать уже существующие записи.",
      "isActive": true
    }
  ]
}

=== BaSysTeam/BaSYS.Examples.ContractApproval/metadata/workflow/fill_person/workflow.fill_person.json
{
  "$schema": "../../system/schemas/workflowSettings.schema.json",
  "uid": "a1b2c3d4-e5f6-4a7b-8c9d-001122334455",
  "name": "fill_person",
  "title": "01.004 Заполнение физических лиц",
  "memo": "Первоначальное заполнение справочника физических лиц тестовыми ФИО.",
  "isActive": true,
  "version": 4,
  "parameters": [],
  "steps": [
    {
      "expression": "workflow.fill_person.step.data.bjs",
      "uid": "b2c3d4e5-f6a7-4b8c-9d0e-112233445566",
      "previousStepUid": "",
      "kindUid": "dff616ce-0f40-4e44-a82b-14aa5ee2e4d6",
      "kindName": "java_script",
      "title": "Данные",
      "name": "data",
      "memo": "Подготовка DataTable со списком физических лиц для загрузки.",
      "isActive": true
    },
    {
      "metaObjectKindUid": "032d8377-500f-4631-b435-1f7f69046674",
      "metaObjectUid": "7c3e1f92-4d8a-4b2e-9a1c-6f5e2d3b4a01",
      "saveRegime": 1,
      "searchBy": "title",
      "sourcePath": "data",
      "condition": "",
      "createRecords": false,
      "skipHistory": false,
      "headerMapping": [
        {
          "uid": "d4e5f6a7-b8c9-4d0e-1f2a-334455667788",
          "sourceFieldName": "last_name",
          "destinationFieldName": "last_name",
          "defaultValue": "",
          "searchBy": "",
          "dataTypeUid": "0234c067-7868-46b2-ba8e-e22fae5255cb",
          "createIfNotExist": false
        },
        {
          "uid": "e5f6a7b8-c9d0-4e1f-2a3b-445566778899",
          "sourceFieldName": "first_name",
          "destinationFieldName": "first_name",
          "defaultValue": "",
          "searchBy": "",
          "dataTypeUid": "0234c067-7868-46b2-ba8e-e22fae5255cb",
          "createIfNotExist": false
        },
        {
          "uid": "f6a7b8c9-d0e1-4f2a-3b4c-556677889900",
          "sourceFieldName": "middle_name",
          "destinationFieldName": "middle_name",
          "defaultValue": "",
          "searchBy": "",
          "dataTypeUid": "0234c067-7868-46b2-ba8e-e22fae5255cb",
          "createIfNotExist": false
        },
        {
          "uid": "a7b8c9d0-e1f2-4a3b-4c5d-667788990011",
          "sourceFieldName": "title",
          "destinationFieldName": "title",
          "defaultValue": "",
          "searchBy": "",
          "dataTypeUid": "0234c067-7868-46b2-ba8e-e22fae5255cb",
          "createIfNotExist": false
        }
      ],
      "tableMapping": [],
      "uid": "c3d4e5f6-a7b8-4c9d-0e1f-223344556677",
      "previousStepUid": "b2c3d4e5-f6a7-4b8c-9d0e-112233445566",
      "kindUid": "a7edd0be-6f12-4fac-b88a-4f83acc7dacb",
      "kindName": "data_object_loader",
      "title": "Загрузка данных",
      "name": "load",
      "memo": "Создание физических лиц. Режим Create — повторный запуск не задублирует существующие записи.",
      "isActive": true
    }
  ]
}

=== BaSysTeam/BaSYS.Examples.ContractApproval/metadata/workflow/fill_contract_status/workflow.fill_contract_status.json
{
  "$schema": "../../system/schemas/workflowSettings.schema.json",
  "uid": "c6b8d2e4-3a9f-4d6e-8b2c-7f4e1d3a8c5b",
  "name": "fill_contract_status",
  "title": "01.002 Заполнение статусов договоров",
  "memo": "Первоначальное заполнение перечисления contract_status стандартными значениями.",
  "isActive": true,
  "version": 2,
  "parameters": [],
  "steps": [
    {
      "expression": "workflow.fill_contract_status.step.data.bjs",
      "uid": "d7c9e3f5-4baf-4e7f-9c3d-8a5f2e4b9d6c",
      "previousStepUid": "",
      "kindUid": "dff616ce-0f40-4e44-a82b-14aa5ee2e4d6",
      "kindName": "java_script",
      "title": "Данные",
      "name": "data",
      "memo": "Подготовка DataTable со значениями статусов договоров.",
      "isActive": true
    },
    {
      "metaObjectKindUid": "5449a8ad-9359-41b2-8ff2-3f415eb4da76",
      "metaObjectUid": "a3f1b8e2-7c4d-4a5b-9e6f-1d2c3b4a5e6f",
      "saveRegime": 1,
      "searchBy": "name",
      "sourcePath": "data",
      "condition": "",
      "createRecords": false,
      "skipHistory": false,
      "headerMapping": [
        {
          "uid": "f9eb0517-6dc1-4091-ae5f-ac7a4b6dbf8e",
          "sourceFieldName": "name",
          "destinationFieldName": "name",
          "defaultValue": "",
          "searchBy": "",
          "dataTypeUid": "0234c067-7868-46b2-ba8e-e22fae5255cb",
          "createIfNotExist": false
        },
        {
          "uid": "a0fc1628-7ed2-41a2-bf60-bd8b5c7eca9f",
          "sourceFieldName": "code",
          "destinationFieldName": "code",
          "defaultValue": "",
          "searchBy": "",
          "dataTypeUid": "0234c067-7868-46b2-ba8e-e22fae5255cb",
          "createIfNotExist": false
        },
        {
          "uid": "b10d2739-8fe3-42b3-c071-ce9c6d8fdba0",
          "sourceFieldName": "title",
          "destinationFieldName": "title",
          "defaultValue": "",
          "searchBy": "",
          "dataTypeUid": "0234c067-7868-46b2-ba8e-e22fae5255cb",
          "createIfNotExist": false
        }
      ],
      "tableMapping": [],
      "uid": "e8daf406-5cb0-4f80-9d4e-9b6f3a5cae7d",
      "previousStepUid": "d7c9e3f5-4baf-4e7f-9c3d-8a5f2e4b9d6c",
      "kindUid": "a7edd0be-6f12-4fac-b88a-4f83acc7dacb",
      "kindName": "data_object_loader",
      "title": "Загрузка данных",
      "name": "load",
      "memo": "Создание значений перечисления contract_status. Режим Create, чтобы не задублировать уже существующие записи.",
      "isActive": true
    }
  ]
}
